apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: auto-endpoints-discover
spec:
  discoveryRole: endpoints
  endpoints:
  - relabelConfigs:
    - sourceLabels: [__address__,__meta_kubernetes_pod_container_port_number]
      action: replace
      targetLabel: __address__
      regex: ([^:]+)(?::\d+)?;(\d+)  # RE2 正则规则，+是一次多多次，?是0次或1次，其中?:表示非匹配组(意思就是不获取匹配结果)
      replacement: $1:$2
    - source_labels: [__scheme__]
      action: replace
      targetLabel: __scheme__
      regex: "(https?)"
    - action: labelmap
      regex: "[__meta_kubernetes_service_label_(.+)]"
      replacement: $1
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: kubernetes_namespace
    - sourceLabels: [__meta_kubernetes_service_name]
      action: replace
      targetLabel: kubernetes_service
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: kubernetes_pod
    - sourceLabels: [__meta_kubernetes_endpoint_node_name]
      action: replace
      targetLabel: kubernetes_node
