apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      # 配置邮件发送信息
      smtp_smarthost: 'smtp.163.com:25'
      smtp_from: '[ethan1437@163.com]'  # 163邮箱地址
      smtp_auth_username: '[ethan1437@163.com]'
      smtp_auth_password: 'GINLWGUEXNLCEQLF'  # 使用网易邮箱的授权码
      smtp_hello: '163.com'
      smtp_require_tls: false
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'webhook'
      routes:
      - receiver: email
        group_wait: 10s
        match:
          team: node
    receivers:
    - name: 'default'
      email_configs:
      - to: '[ethan1437@163.com]'
        send_resolved: true  # 接受告警恢复的通知
    - name: 'webhook'
      email_configs:
      - to: '[ethan1437@163.com]'
        send_resolved: true
