apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vmalert
  namespace: vm-single
spec:
  replicaCount: 1
  datasource:
    url: "http://vmsingle-vmsingle.vm-single.svc:8429"
  notifier:
      url: "http://vmalertmanager-alertmanager.vm-single.svc:9093"
  evaluationInterval: "30s"
  selectAllByDefault: true