apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  name: httpPost-probe
  namespace: vm-single
spec:
  jobName: httpPost-item      # 定义任务名称
  vmProberSpec:
    url: prometheus-blackbox-exporter.vm-single.svc:9115   #指定blackbox-exporter地址
  module: http_2xx                 #配置文件中的检测模块
  targets:                                          #抓取目标配置
   # ingress <Object>
   staticConfig:          #如果配置了 ingress，静态配置优先
      targets:
      - http://192.168.12.5:9090/-/reload
      labels:
        group: "service"
      relabelingConfigs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
  interval: 2s 