apiVersion: operator.victoriametrics.com/v1beta1
kind: VMProbe
metadata:
  name: tcp-prot-probe
  namespace: vm-single
spec:
  jobName: tcp-prot-item      # 定义任务名称
  vmProberSpec:
    url: prometheus-blackbox-exporter.vm-single.svc:9115   #指定blackbox-exporter地址
  module: tcp_connect                #配置文件中的检测模块
  targets:                                          #抓取目标配置
   # ingress <Object>
   staticConfig:          #如果配置了 ingress，静态配置优先
      targets:
      - 192.168.39.12:3306
      - 192.168.39.11:22
      labels:
        group: "TCP"
        instance: "port-status"
      relabelingConfigs:
      - source_labels: [__address__]
        target_label: __param_target
  interval: 2s 