# prometheus-rules.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: kube-mon
data:
  alert-rules.yaml: |-
    groups:
      - name: K8sObjects_Alerts
        rules:
        - alert: Deployment_Replicas_0
          expr: |
            sum(kube_deployment_status_replicas) by (deployment, namespace) < 1
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: Deployment {{$labels.deployment}} of {{$labels.namespace}} is currently having no pods running
            description: Has no pods running in Deployment {{$labels.deployment}} of {{$labels.namespace}}, you can describe to get events, or get replicas status.
