apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vmsingle
  namespace: vm-single
spec:
  replicaCount: 1
  retentionPeriod: "1w"
  removePvcAfterDelete: true
  storage:
    storageClassName: "longhorn"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vmsingle
  namespace: vm-single
spec:
  ingressClassName: nginx
  rules:
  - host: vmsingle.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vmsingle
            port:
              number: 8429

