apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
  name: kube-state-metrics
spec:
  endpoints:
  - path: /metrics
    targetPort: 8080
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
