apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-blackbox-exporter
  namespace: vm-single
  labels:
    app: prometheus-blackbox-exporter
data:
  blackbox.yaml: |
    modules:
      http_2xx:
        http:
          preferred_ip_protocol: ip4
          valid_http_versions: [HTTP/1.1, HTTP/2]
          method: GET
        prober: http
        timeout: 5s
      http_post_2xx: # POST 请求
        http:
          method: POST
          preferred_ip_protocol: ip4
        prober: http
      tcp_connect: # tcp 连接
        prober: tcp
        timeout: 10s
        tcp:
          preferred_ip_protocol: ip4
      dns:  # DNS 检测模块
        prober: dns
        dns:
          transport_protocol: udp  # 默认是 udp，tcp
          preferred_ip_protocol: ip4  # 默认是 ip6
          query_name: kubernetes.default.svc.cluster.local # 利用这个域名来检查dns服务器
      icmp:  # ping 检测服务器的存活
        prober: icmp
      
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-blackbox-exporter
  namespace: vm-single
  labels:
    app: prometheus-blackbox-exporter
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9115
      protocol: TCP
  selector:
    app: prometheus-blackbox-exporter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vm-single
  name: prometheus-blackbox-exporter
  labels:
    app: prometheus-blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-blackbox-exporter
  template:
    metadata:
      labels:
        app: prometheus-blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:v0.17.0
          args:
            - --config.file=/config/blackbox.yaml
          resources:
            {}
          ports:
            - containerPort: 9115
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          configMap:
            name: prometheus-blackbox-exporter