apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: kube-state-metrics
spec:
  podMetricsEndpoints:
    - port: "8080"
      scheme: http
  selector:
    matchLabels:
     app.kubernetes.io/name: kube-state-metrics